version: 1
formatters:
  main:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
  console:
    format: '%(asctime)s %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
    level: INFO
loggers:
  nemory:
    # Logger itself is set at DEBUG level, but the default console handler is set to INFO
    level: DEBUG
    propagate: false
    handlers: [ console ]