# Extend the `pyproject.toml` file in the parent directory.
extend = "pyproject.toml"
# But use a different line length.
line-length = 120

[lint]
extend-select = [
    # pydoclint
    "DOC",
    # pydocstyle
    "D",
    "I",
    "T20",
    "S",
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "S404", # excluded because there is other subchecks on the usage of subprocess
    "S608", # excluded because we're builidng a lot of SQL queries using formatted strings for reusability (without using user input variables)
]
preview = true

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"

[lint.pydoclint]
# Skip docstrings which fit on a single line.
ignore-one-line-docstrings = true

[lint.per-file-ignores]
# Ignore `D` and "DOC" rules everywhere except for the `src/` directory.
"!src/**.py" = ["D", "DOC", "T20", "S"]
