# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python CI

permissions: { }

on:
  push:
    paths-ignore:
      - docs/
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - docs/
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: "Build project and run unit tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      # in GitHub workflows, we don't let uv manage python installations since it could be slower
      # because GitHub caches the Python versions alongside the runner.
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.7"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff checks
        run: uv run ruff check
        
      - name: Run ruff format
        run: uv run ruff format --check

      - name: Run tests
        run: uv run pytest

      - name: Build
        run: |
          uv build