name: Python Tests

permissions: { }

on:
  push:
    paths-ignore:
      - docs/
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - docs/
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit:
    name: Run pytest on ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up project
        uses: ./.github/actions/setup-project
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up ollama
        uses: ./.github/actions/install-and-run-ollama-with-model

      - name: Run pytest
        run: uv run pytest -v